# ==============================================================================
# Cloud Build - dbt Run Configuration
# ==============================================================================
# Ejecuta dbt run + test + apply policy tags
# Trigger: Cloud Scheduler (post-ingesta) o manual
# ==============================================================================

steps:
  # Step 1: Install uv and dependencies
  - name: 'python:3.11-slim'
    id: 'install-deps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git
        pip install uv
        uv sync
    dir: 'Desafio_2/dbt'

  # Step 2: dbt run (incremental)
  - name: 'python:3.11-slim'
    id: 'dbt-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git
        pip install uv
        uv run dbt run --profiles-dir .
    dir: 'Desafio_2/dbt'
    waitFor: ['install-deps']

  # Step 3: dbt test
  - name: 'python:3.11-slim'
    id: 'dbt-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git
        pip install uv
        uv run dbt test --profiles-dir .
    dir: 'Desafio_2/dbt'
    waitFor: ['dbt-run']

  # Step 4: Apply policy tags (post-dbt)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'apply-policy-tags'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x Desafio_2/scripts/apply_policy_tags.sh
        cd Desafio_2/scripts && ./apply_policy_tags.sh || echo "Policy tags skipped (requires terraform)"
    waitFor: ['dbt-test']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'  # 30 minutos máximo
